spring:
  application:
    name: PC-SERVICE

  datasource:
    url: jdbc:postgresql://dpg-d08h32be5dus73ehqf6g-a.oregon-postgres.render.com/pc_club_db
    username: root
    password: Cm7tgKzBKERCKH5acn7qLwfhP1UCNDzX
    driver-class-name: org.postgresql.Driver

  config:
    import: optional:configserver:http://localhost:8888

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8091


logging:
  level:
    org:
      springframework:
        web: DEBUG
    root: INFO

