version: '3.8'

services:
  # Eureka Discovery Server
  eureka-server:
    build:
      context: ./discovery  # Путь до папки, где лежит Dockerfile для eureka
    container_name: eureka-server
    environment:
      - spring.application.name=DISCOVERY
    networks:
      - pc-club-network
    restart: always

  # AUTH-SERVICE
  auth-service:
    build:
      context: ./Auth_Service
    container_name: auth-service
    environment:
      - spring.application.name=AUTH-SERVICE
    depends_on:
      - eureka-server
    entrypoint: /bin/sh -c "sleep 60 && java -jar /app/app.jar"  # Задержка 3 минуты
    networks:
      - pc-club-network
    restart: always

  # CLIENT-SERVICE
  client-service:
    build:
      context: ./Client_Service
    container_name: client-service
    environment:
      - spring.application.name=CLIENT-SERVICE
    depends_on:
      - eureka-server
    entrypoint: /bin/sh -c "sleep 60 && java -jar /app/app.jar"  # Задержка 3 минуты
    networks:
      - pc-club-network
    restart: always

  # ORDER-SERVICE
  order-service:
    build:
      context: ./Order_Service
    container_name: order-service
    environment:
      - spring.application.name=ORDER-SERVICE
    depends_on:
      - eureka-server
    entrypoint: /bin/sh -c "sleep 60 && java -jar /app/app.jar"  # Задержка 3 минуты
    networks:
      - pc-club-network
    restart: always

  # PAYMENT-SERVICE
  payment-service:
    build:
      context: ./Payment_Service
    container_name: payment-service
    environment:
      - spring.application.name=PAYMENT-SERVICE
    depends_on:
      - eureka-server
    entrypoint: /bin/sh -c "sleep 60 && java -jar /app/app.jar"  # Задержка 3 минуты
    networks:
      - pc-club-network
    restart: always

  # PC-SERVICE
  pc-service:
    build:
      context: ./PC_Service
    container_name: pc-service
    environment:
      - spring.application.name=PC-SERVICE
    depends_on:
      - eureka-server
    entrypoint: /bin/sh -c "sleep 60 && java -jar /app/app.jar"  # Задержка 3 минуты
    networks:
      - pc-club-network
    restart: always

  # Gateway
  gateway:
    build:
      context: ./gateway
    container_name: gateway
    environment:
      - spring.application.name=GATEWAY
    ports:
      - "8966:8966"
    depends_on:
      - eureka-server
    entrypoint: /bin/sh -c "sleep 60 && java -jar /app/app.jar"  # Задержка 3 минуты
    networks:
      - pc-club-network
    restart: always

networks:
  pc-club-network:
    driver: bridge
