spring:
  application:
    name: ORDER-SERVICE

  datasource:
    url: jdbc:postgresql://dpg-d08h32be5dus73ehqf6g-a.oregon-postgres.render.com/pc_club_db
    username: root
    password: Cm7tgKzBKERCKH5acn7qLwfhP1UCNDzX
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Europe/Moscow
  jackson:
    time-zone: Europe/Moscow

  config:
    import: optional:configserver:http://localhost:8888

  jackson:
    time-zone: "Europe/Moscow"


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8094


logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      PCCLub:
        Order_Service: DEBUG
    root: INFO
