spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/pc_club_db
    username: postgres
    password: 915327
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: optional:configserver:http://localhost:8888

  jackson:
    time-zone: "Europe/Moscow"

eureka:
  client:
    instance:
      hostname: localhost
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret_key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  life_time: 86400000

server:
  port: 8095


logging:
  level:
    org:
      springframework:
        web: DEBUG
    root: INFO